title: Help | Cloud 66
email: support@cloud66.com
permalink: /:collection/:path/

collections:
  general:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  legacy_docker:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  maestro:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  node:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  rails:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  skycap:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
# Build settings
markdown: kramdown

sass:
    style:  compressed  # nested|expanded|compact|compressed

safe: false

plugins:
  - algoliasearch-jekyll

algolia:
  application_id: 'TXUI53WBEH'
  index_name:     'help'
  record_css_selector: 'p,ul'
  settings:
    attributesToSnippet: ['raw_html:100']
    attributeForDistinct: 'title'
    distinct: true
    removeWordsIfNoResults: 'lastWords'

